### ISSUE TITLE
librarian-puppet support

### ISSUE THREAD

**Issue by ascott97** [sonatype-nexus-community/nexus-repository-puppet#3]
* **What are you trying to do?**
Install puppet modules from a nexus server with this plugin using librarian-puppet(v2.2.3)

* **What feature or behavior is this required for?**
We wish to install puppet modules via librarian-puppet, currently we have a working version of this plugin installing via `puppet module install`

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**
Verbose output from librarian-puppet run is attached.

[librarian-puppet-run.txt](https://github.com/sonatype-nexus-community/nexus-repository-puppet/files/2595041/out.txt)

**Comment by DarthHater** [comment]
Thanks for reporting this! I'll see if I can take a gander.

**Comment by DarthHater** [comment]
Ok I see what the issue is, it looks like librarian-puppet is doing a call like:

`[Librarian] Querying Forge API for module puppetlabs-stdlib: https://nexus-url/repository/puppet/api/v1/releases.json?module=puppetlabs/stdlib`

The route we implemented only supports something like:

`[Librarian] Querying Forge API for module puppetlabs-stdlib: https://nexus-url/repository/puppet/api/v3/releases?module=puppetlabs/stdlib`

So it's two fold, librarian-puppet is using v1 of the Puppet Forge API by the looks of it, where as we implemented support for explicitly v3. That and the .json would throw off our route, too, since we match only on `/v3/releases`.

From the package:

```
Versions
Librarian-puppet >= 2.0 (as well as 1.1, 1.2 and 1.3) requires Ruby 1.9 and uses the Puppet Forge API v3. Versions < 2.0 work on Ruby 1.8.
```

So it using v1 is odd, to say the least. From the looks of it, you should be able to sidestep this like:

`librarian-puppet install --no-use-v1-api # use the v3 API; default for official Puppet Forge`

**Comment by DarthHater** [comment]
Also, if that works for you, feel free to send a PR to our docs for this project on how to use `librarian-puppet`, as I'm sure it would be helpful for others :)

**Comment by DarthHater** [comment]
That help at all @ascott97 ?

**Comment by zlahham** [comment]
@DarthHater thanks for looking into this. 

Apologies for the delay in the replying. I do remember running `librarian-puppet install --no-use-v1-api` before @ascott97 submitted the PR with no immediate fix - as `librarian-puppet` uses v1 of the Puppet Forge API by default.

I'll give it another shot and ping you, thanks!

**Comment by AtilaSuleyman** [comment]
Hi @DarthHater, apologise for the time taken to update you on our situation.

after adding the ```--no-use-v1-api``` to the librarian puppet install command I have still found that this does not fix the issue. 

Environment I use:
* Docker Container which uses a centos image

Method 1 (Without the use of Nexus):
* Puppetfile that uses ```https://forgeapi.puppetlabs.com``` as the 'forge' to pull puppet modules from
* Ran ```bundle exec librarian-puppet install --no-use-v1-api --verbose``` (to use api v3)
This method worked as expected.

Method 2 (Install via Nexus):
* Inserted ```module_repository = 'https://<nexus-url>/repository/puppetrepo``` into ```puppet.conf```
* Set 'forge' to ```https://<nexus-url>/repository/puppetrepo``` (have also tried it keeping 'forge' set to ```https://forgeapi.puppetlabs.com```) 

The results using method 2 can be found below, first time was run using apiv1 the second using apiv3
[v1api.txt](https://github.com/sonatype-nexus-community/nexus-repository-puppet/files/2644524/v1api.txt)
[v3api.txt](https://github.com/sonatype-nexus-community/nexus-repository-puppet/files/2644527/v3api.txt)

I would be very grateful if you can help us further with this issue.

**Comment by DarthHater** [comment]
This may or may not be fixed with: https://github.com/sonatype-nexus-community/nexus-repository-puppet/tree/ModulesEndpoint

Looks like `librarian-puppet` uses one more endpoint that we didn't implement. Go ahead and build, and test! I got it working locally but I'm no puppet wiz.

**Comment by AtilaSuleyman** [comment]
@DarthHater Thanks a lot for your quick response times and your help, I have tried it using a ```librarian-puppet install --no-use-v1-api``` and it works with Nexus as I would expect. I am going to create a new branch of 'ModulesEndpoint' and update the README to say that ```librarian-puppet``` is now supported by the plugin

**Comment by DarthHater** [comment]
Awesome!!!
